/*
Pr No: 06
Title: The symbol table is generated by compiler. From this perspective, the symbol table is a set of
	name-attribute pairs. In a symbol table for a compiler, the name is an identifier, and the
	attributes might include an initial value and a list of lines that use the identifier.
	Perform the following operations on symbol table:
	(1) Determine if a particular name is in the table
	(2) Retrieve the attributes of that name
	(3) Modify the attributes of that name
	(4) Insert a new name and its attributes
	(5) Delete a name and its attributes
Batch:  'C' 
Roll No: 46
Class:  SE Computer Engineering
Started On: 02-Feb-2018
Complted On: 02-Feb-2018
*/

#include<iostream>
#include<string.h>
using namespace std;

int table_size = 10;

class Symbol_Table
{
    char id[20];
    char value[20];
    
    public:

    void create();
    void display();
    void find();
    void del();
    void modify();
}HT[10];


void Symbol_Table :: create()
{
    int i, j, askii, index, records;
    char id[20], value[20];
    
    cout<<"\n\n\t How many (Identifier, value) Pairs: ";
    cin>>records;
    
    for(i=0; i<records; i++) 
    {
       cout<<"\n\n Enter (Identifier, value) Pair_"<<i+1<<" :";
       
       cout<<"\n\n\t Enter Identifier : ";
       cin>>id;
       cout<<"\n\n\t Enter Value : ";
       cin>>value;
       
       askii = 0;
       
       for(j=0; id[j] != '\0'; j++)
       {
          askii = askii + id[j]; 
       }
       
       index = askii % table_size;
       
       strcpy( HT[index].id , id );
       strcpy( HT[index].value , value );
    }
}

void Symbol_Table :: display()
{
   int i;
   
   cout<<"\n\n\t Index  Identifier  Value";
   for(i=0; i<table_size; i++)
   {
       cout<<"\n\t   "<<i;
       cout<<"       "<<HT[i].id;
       cout<<"       "<<HT[i].value;              
   }
}

void Symbol_Table :: find()
{
       
   int i, j, index, askii;
   char id[20];
       
   cout<<"\n\n\t Enter Identifier : ";
   cin>>id;
       
   askii = 0;
       
   for(j=0; id[j] != '\0'; j++)
   {
       askii = askii + id[j]; 
   }
       
   index = askii % table_size;
   
   cout<<"\n\n\t The Value is : "<<HT[index].value;
}
  
    
void Symbol_Table :: del()
{
   int i, j, index, askii;
   char id[20];
       
   cout<<"\n\n\t Enter Identifier : ";
   cin>>id;
       
   askii = 0;
       
   for(j=0; id[j] != '\0'; j++)
   {
       askii = askii + id[j]; 
   }
       
   index = askii % table_size;
   
   strcpy( HT[index].id , "" );
   strcpy( HT[index].value , "" );
   
   cout<<"\n\n\t The (id,value) pair is deleted !!!";
}
   
void Symbol_Table :: modify()
{
   int i, j, index, askii;
   char id[20];
       
   cout<<"\n\n\t Enter Identifier : ";
   cin>>id;
       
   askii = 0;
       
   for(j=0; id[j] != '\0'; j++)
   {
       askii = askii + id[j]; 
   }
       
   index = askii % table_size;
   
   cout<<"\n\n\t Enter new Identifier : ";
   cin>>id;
   
   askii = 0;
       
   for(j=0; id[j] != '\0'; j++)
   {
       askii = askii + id[j]; 
   }
       
   index = askii % table_size;
   
   strcpy(HT[index].id , id);
   cout<<"\n\n\t Enter new Value : ";   
   cin>>HT[index].value;
   
   cout<<"\n\n\t The (id,value) pair is updated !!!";
}



int main()
{
   int i,ch;
   char ans;
   
   Symbol_Table D1;
   cout<<"\n\n --------------- The Symbol Table implemented by Hash Table --------------";
   do
   {
       cout<<"\n\n ***** Menu *****";
       cout<<"\n\n 1. Create Symbol_Table";
       cout<<"\n\n 2. Display Symbol_Table";
       cout<<"\n\n 3. Find/Search in Symbol_Table";
       cout<<"\n\n 4. Delete from Symbol_Table";
       cout<<"\n\n 5. Modify Symbol_Table";  
       
       cout<<"\n\n\t Enter Your Choice: ";
       cin>>ch;
       
       switch(ch)
       {
          case 1: D1.create();
          	  break;
          	  
          case 2: D1.display();
          	  break;
          	  
          case 3: D1.find();
          	  break;
          	  
          case 4: D1.del();
          	  break;
          	  
          case 5: D1.modify();
          	  break;
          	  
          default: cout<<"\n\n\t Wrong Choice !!!";
       }
       
       cout<<"\n\n Do you wanna continue? (y/n) : ";
       cin>>ans;
       
                                               
   }while(ans == 'y' || ans == 'Y');
   
   return 0;
}



/*----------------OUTPUT--------------------------
student@IOE-L1LAB:~$ g++ Pr_6BC.cpp -o a
student@IOE-L1LAB:~$ ./a


 --------------- The Symbol Table implemented by Hash Table --------------

 ***** Menu *****

 1. Create Symbol_Table

 2. Display Symbol_Table

 3. Find/Search in Symbol_Table

 4. Delete from Symbol_Table

 5. Modify Symbol_Table

	 Enter Your Choice: 1


	 How many (Identifier, value) Pairs: 3


 Enter (Identifier, value) Pair_1 :

	 Enter Identifier : a


	 Enter Value : 10


 Enter (Identifier, value) Pair_2 :

	 Enter Identifier : b


	 Enter Value : 20


 Enter (Identifier, value) Pair_3 :

	 Enter Identifier : sum


	 Enter Value : 0


 Do you wanna continue? (y/n) : y


 ***** Menu *****

 1. Create Symbol_Table

 2. Display Symbol_Table

 3. Find/Search in Symbol_Table

 4. Delete from Symbol_Table

 5. Modify Symbol_Table

	 Enter Your Choice: 2


	 Index  Identifier  Value
	   0              
	   1       sum       0
	   2              
	   3              
	   4              
	   5              
	   6              
	   7       a       10
	   8       b       20
	   9              

 Do you wanna continue? (y/n) : y


 ***** Menu *****

 1. Create Symbol_Table

 2. Display Symbol_Table

 3. Find/Search in Symbol_Table

 4. Delete from Symbol_Table

 5. Modify Symbol_Table

	 Enter Your Choice: 3


	 Enter Identifier : sum


	 The Value is : 0

 Do you wanna continue? (y/n) : y


 ***** Menu *****

 1. Create Symbol_Table

 2. Display Symbol_Table

 3. Find/Search in Symbol_Table

 4. Delete from Symbol_Table

 5. Modify Symbol_Table

	 Enter Your Choice: 5


	 Enter Identifier : sum


	 Enter new Identifier : sum


	 Enter new Value : 30


	 The (id,value) pair is updated !!!

 Do you wanna continue? (y/n) : y


 ***** Menu *****

 1. Create Symbol_Table

 2. Display Symbol_Table

 3. Find/Search in Symbol_Table

 4. Delete from Symbol_Table

 5. Modify Symbol_Table

	 Enter Your Choice: 2


	 Index  Identifier  Value
	   0              
	   1       sum       30
	   2              
	   3              
	   4              
	   5              
	   6              
	   7       a       10
	   8       b       20
	   9              

 Do you wanna continue? (y/n) : y


 ***** Menu *****

 1. Create Symbol_Table

 2. Display Symbol_Table

 3. Find/Search in Symbol_Table

 4. Delete from Symbol_Table

 5. Modify Symbol_Table

	 Enter Your Choice: 4


	 Enter Identifier : sum


	 The (id,value) pair is deleted !!!

 Do you wanna continue? (y/n) : y


 ***** Menu *****

 1. Create Symbol_Table

 2. Display Symbol_Table

 3. Find/Search in Symbol_Table

 4. Delete from Symbol_Table

 5. Modify Symbol_Table

	 Enter Your Choice: 2


	 Index  Identifier  Value
	   0              
	   1              
	   2              
	   3              
	   4              
	   5              
	   6              
	   7       a       10
	   8       b       20
	   9              

 Do you wanna continue? (y/n) : y


 ***** Menu *****

 1. Create Symbol_Table

 2. Display Symbol_Table

 3. Find/Search in Symbol_Table

 4. Delete from Symbol_Table

 5. Modify Symbol_Table

	 Enter Your Choice: 6


	 Wrong Choice !!!

 Do you wanna continue? (y/n) : n
student@IOE-L1LAB:~$
-----------------------------------------------------------------*/
